services:
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
    networks:
      - front-tier
      - back-tier
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://0.0.0.0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-cluster-token
      - etcd-cluster-1
      - -initial-cluster
      - etcd0=http://localhost:2380
      - -initial-cluster-state
      - new

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: control
      POSTGRES_PASSWORD: control
      POSTGRES_DB: control
    networks:
      - back-tier

  control:
    image: amazoncorretto:17
    ports:
      - 9090:9090
    networks:
      - back-tier
    volumes:
      - ../control/build/install/control:/control
      - ./src/test/resources:/config
      - ./build/docker-log:/tmp/logs
    command: ["/control/bin/control", "server", "/config/control-config.yaml"]
    depends_on:
      etcd:
        condition: service_started
      database:
        condition: service_started

  node:
    image: amazoncorretto:17
    ports:
      - 9080:9080
    networks:
      - front-tier
      - back-tier
    volumes:
      - ../node/build/install/node:/node
      - ./src/test/resources:/config
      - ./build/docker-log:/tmp/logs
    command: ["/node/bin/node", "server", "/config/node-config.yaml"]
    depends_on:
      etcd:
        condition: service_started
      database:
        condition: service_started
      control:
        condition: service_started

networks:
  back-tier: {}
  front-tier: {}