services:
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
    volumes:
      - etcd0:/etcd_data
    networks:
      - front-tier

    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://0.0.0.0:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-cluster-token
      - etcd-cluster-1
      - -initial-cluster
      - etcd0=http://localhost:2380
      - -initial-cluster-state
      - new

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: control
      POSTGRES_PASSWORD: control
      POSTGRES_DB: control
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    networks:
      - front-tier

  control:
    image: amazoncorretto:17
    configs:
      - control-config
    ports:
      - 9090:9090
    networks:
      - front-tier
    volumes:
      - ./control/build/install/control:/control
    command: ["/control/bin/control", "server", "/config/control-config.yaml"]
    depends_on:
      etcd:
        condition: service_started
      database:
        condition: service_started

volumes:
  etcd0:

configs:
  control-config:
    file: config/control-config.yaml

networks:
  back-tier: {}
  front-tier: {}