logging:
  level: INFO
  loggers:
    com.codeheadsystems: DEBUG
    com.codeheadsystems.dstore: TRACE
    com.codeheadsystems.dstore.control.healthchecks: INFO
    com.codeheadsystems.dstore.common.config.healthchecks: INFO
    com.mchange.v2.c3p0: WARN
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] [trace:%X{trace}] %-5level %logger{36} - %msg%n"

# A test db for now, hsql. Also, we will use liquibase by default in the config file. Production won't do this.
runLiquibase: true
database:
  driverClass: org.hsqldb.jdbc.JDBCDriver
  user: SA
  password: ""
  url: jdbc:hsqldb:mem:database
  validationQuery: "/* MyService Health Check */ call now()"
# Validation query note: HSQL is weird. We won't have to do this with postgresql.

metrics:
  frequency: 1 minute
  reportOnStop: true
  reporters:
    - type: log
      logger: metrics
      markerName: SLF4j
#    - type: graphite
#      host: localhost
#      port: 2003
#      prefix: node
#      transport: tcp

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

etcdConfiguration:
  target: ip:///localhost:2379

health:
  healthCheckUrlPaths: [ "/health-check" ]
  healthChecks:
    - name: deadlocks
      type: alive
      critical: true
      initialState: true
      schedule:
        checkInterval: 10s
        downtimeInterval: 2s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2
    - name: database
      type: alive
      critical: true
      initialState: true
      schedule:
        checkInterval: 10s
        downtimeInterval: 2s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2