databaseDirectory: /server/work
runDatabaseInMemory: false
controlPlaneUrl: http://control:8080/
nodePort: 8080

logging:
  level: INFO
  loggers:
    org.svarm: TRACE
    org.svarm.node.healthchecks: INFO
    org.svarm.common.config.healthchecks: INFO
    com.mchange.v2.c3p0: WARN
  appenders:
    - type: console
      logFormat: "%d{HH:mm:ss.SSS} [%thread] [trace:%X{trace}] %-5level %logger{36} - %msg%n"
    - type: file
      maxFileSize: 50MB
      currentLogFilename: /server/logs/node.log
      archivedLogFilenamePattern: /server/logs/node-%i.log.gz
      logFormat: "%d{HH:mm:ss.SSS} [%thread] [trace:%X{trace}] %-5level %logger{36} - %msg%n"

#metrics:
#  frequency: 1 minute
#  reportOnStop: true
#  reporters:
#    - type: log
#      logger: metrics
#      markerName: SLF4j
#    - type: graphite
#      host: localhost
#      port: 2003
#      prefix: node
#      transport: tcp

server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

etcdConfiguration:
  target: ip:///etcd:2379

health:
  healthCheckUrlPaths: [ "/health-check" ]
  healthChecks:
    - name: deadlocks
      type: alive
      critical: true
      initialState: true
      schedule:
        checkInterval: 60s
        downtimeInterval: 10s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2
    - name: InternalDataSourceHealthCheck
      type: ready
      critical: true
      initialState: false
      schedule:
        checkInterval: 60s
        downtimeInterval: 10s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2
    - name: TenantTablelJdbiHealthCheck
      type: ready
      critical: true
      initialState: false
      schedule:
        checkInterval: 60s
        downtimeInterval: 10s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2
    - name: BasicHealthCheck
      type: alive
      critical: true
      initialState: false
      schedule:
        checkInterval: 60s
        downtimeInterval: 10s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2
    - name: EtcdHealthCheck
      type: alive
      critical: true
      initialState: true
      schedule:
        checkInterval: 60s
        downtimeInterval: 10s
        initialDelay: 5s
        failureAttempts: 1
        successAttempts: 2